metadaten:
  show_name: Physikshow Gone Wild
  veranstaltungsort: Krissis Wohnung
  datum: 28.03.26
  sprache: de
  kontakte:
  - name: Vita
    mail: vita@physikshow.uni-bonn.de
    telefon: ''
  - name: Mortis
    mail: mortis@physikshow.uni-bonn.de
    telefon: ''
module:
  experimente: true
  technik: true
  unterkunft: false
  buehne: true
  anreise: true
buehne:
  tische: 4
  stuehle: 0.0
  sonstiges: ''
anreise:
  anreisetag: 31.03.
  ankunftszeit: '14:00'
  crew_groesse: 20
  fahrzeuge:
    material_transporter: 2
    personen_transporter: 2
  sonstiges: ''
technik:
  crew:
  - Timo Poller
  - Paula Weber
  - Kristoffer Kerkhof
  kontakte:
  - name: Luna Callisto
    mail: luna@physikshow.uni-bonn.de
    telefon: ''
  bild: true
  licht:
    aktiv: true
    lichtsteuerung_durch_crew: true
    verdunkelung_noetig: true
    spot: true
  ton:
    aktiv: true
    anzahl_mikros: 6
    mischpult: true
  sonstiges: ''
experimente:
  kontakte:
  - name: Jupi Mercury
    mail: jupi@physikshow.uni-bonn.de
    telefon: ''
  fluessigstickstoff:
    aktiv: true
    anforderungen:
      liter_benoetigt: 15
  feuertornado:
    aktiv: true
    bilder:
    - Feuertornado_gross.jpeg
    - Feuertornado_gross1.jpeg
    - Feuertornado_klein.jpeg
